### ISSUE TITLE
[Docs] Github Repo 기본 설정

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-accountbook-14#1]
## 📚 To-do

- [x] Issue template 작성
- [x] PR template 작성
- [x] Issue Label 수정

## 🕐 목표 작업 시간

07.26 12:30 - 12:40
## 📆 실제 작업 시간

07.26 12:30 - 12:50
