### ISSUE TITLE
[Feature] 메인 화면 기초 구성

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-accountbook-14#3]
## 📚 To-do

- [x] NoActionBar로 Theme 변경
- [x] BaseActivity 추가
- [x] Bottom Navigation 에 4개의 아이템 추가
- [x] BaseFragment 추가
- [x] ktx 종속성 추가
- [x] 임시로 4개의 Fragment 생성해서 추가

## 🕐 목표 작업 시간

07.26 16:20 - 17:00 (40분)
