### ISSUE TITLE
[Feature] Ledger Data Source, Repository, UseCase 정의(Insert, Fetch 메소드만 추가)

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-accountbook-14#46]
## 📚 To-do

- [x] Data Entity, Domain Model 정의
- [x] Data Source 정의
- [x] Repository 정의
- [x] Fetch List UseCase 정의
- [x] Ledger List 기능과 연동
- [x] Register UseCase 정의
- [x] Register 기능과 연동

## 🕐 목표 작업 시간

07.30 00:00 - 01:00
## 📆 실제 작업 시간

07.30 00:00 - 01:45(fetch list 완료)
07.31 16:00 - 17:00(insert 완료)
