### ISSUE TITLE
[Feature] Ledge List Screen 의 선택모드 처리

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-accountbook-14#61]
### Ledge List Screen 의 선택모드 처리
현재 선택모드 중에 List가 변경되면, 다른 Item인데 선택상태가 유지되는 문제가 존재
ViewModel 에서 선택모드를 종료하는 기능이 추가되어야 한다

## 📚 To-do

- [x] ViewModel 에서 선택모드를 조정할 수 있어야 한다
- [x] List가 변경하는 경우 선택된 Item이 올바르게 유지되어야 한다
- [x] 선택된 item 배경색상 변경
- [x] 선택된 item이 0개가 되면 선택모드 종료
- [x] 선택모드에서는 Item을 클릭하면 선택된 상태로 체크박스가 나타난다.(이때 수정화면으로 이동 이벤트는 발생하지 않는다)
- [x] 타이틀에 선택된 아이템의 개수 표시
- [x] 체크모드를 view에 state를 저장하지 않고 viewHolder에서 저장해서 관리하도록 수정

## 🕐 목표 작업 시간

08.03 하루종일..
## 📆 실제 작업 시간

08.03 19:45 완료
