### ISSUE TITLE
[Feature] Ledge Edit 화면에서 Label Edit 화면으로 이동 기능 추가

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-accountbook-14#62]
## 📚 To-do

- [x] Spinner 의 맨 마지막에 추가하기 Item 추가
- [x] 해당 item을 클릭 시 Label Edit 화면으로 이동
- [x] 백스택 처리를 통해 추가 후, 추가 도중 뒤로가기 기능 수행시 Edit화면으로 돌아오도록 설정
