### ISSUE TITLE
[Fix] Ledger 추가시 요일 버그, Ledger filtering 시 버그 수정

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-accountbook-14#70]
### Ledger 추가시 요일 버그, Ledger filtering 시 버그 수정
 Ledger 추가시 dayOfWeek 가 추가되지 않는 문제 수정
 Ledger filtering 시 day ledger가 비어있는 day item이 제거되지 않는 문제 수정

## 📚 To-do

- [x] Ledger 추가시 dayOfWeek 가 추가되지 않는 문제 수정
- [x] Ledger filtering 시 day ledger가 비어있는 day item이 제거되지 않는 문제 수정
- [x] Ledger filtering 기능을 UseCase로 분리

## 🕐 목표 작업 시간

08.02 01:30 - 01:40
## 📆 실제 작업 시간

08.02 01:30 - 01:40
