### ISSUE TITLE
[Feature] Compose 추가 및 설정 화면 Compose 로 구현

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-accountbook-14#9]
## 📚 To-do

- [x] Compose 추가
- [x] Compose로 설정화면 구현
- [x] ViewModel 과 연동하여 Dummy Data 연동
- [x] ViewModel 과 연동하여 Click Event 전달

## 🕐 목표 작업 시간

07.26 21:30 - 00:00
## 📆 실제 작업 시간

07.26 21:30 - 07.26 01:20
